services:

  db:
    image: mongo:8.0
    container_name: db-report
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: reto
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: report

volumes:
  mongo_volume:
    external: false