spring:
  application:
    name: report
  rabbitmq:
    host: localhost
    port: 5672
    username: bootcamp
    password: "1234"
  data:
    mongodb:
      uri: mongodb://report:1234@localhost:27017/report

adapter:
  clients:
    timeout: 5000
    clients:
      tech:
        base-url: "http://localhost:8080/api/v1"
      capability:
        base-url: "http://localhost:8081/api/v1"
      person:
        base-url: "http://localhost:8083/api/v1"

queue:
  rabbitmq:
    name-created-queue: "report.create.bootcamp"
    name-enrollment-queue: "report.enrollment.bootcamp"